/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "STD_TYPES.h"
#include "BIT_MATH.h"

#include "RCC_interface.h"
#include "GPIO_interface.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


void Delayms(u16 Copy_u16WaitTme);
void APP_voidShiftLiftRight(void);
void APP_voidFatahyYawarda(void);
void APP_voidSnakeEffect(void);

int main(void)
{
	RCC_voidInit();											/* Init  Clock System				*/
	RCC_voidEnablePeripheralClock(RCC_APB2,RCC_GPIOA);		/*Enable PORTA Peripheral Clock		*/
	GPIO_voidSetPortDirection(PORTA, GPIO_OUTPUT_2MHZ_PP);	/* Set PORTA Direction as output	*/
	GPIO_voidSetPortValue(PORTA, 0x00);						/* Set PORTA Init output as 00000000*/				


    /* Loop forever */
	while(1){
		APP_voidShiftLiftRight();
		Delayms(500);
		APP_voidFatahyYawarda();
		Delayms(500);
		APP_voidSnakeEffect();
		Delayms(500);

	}
	return 0;
}

void Delayms(u16 Copy_u16WaitTme){
	for(u16 i=0;i<Copy_u16WaitTme;i++){
		for(u16 j=0;j<Copy_u16WaitTme;j++){
		asm	("NOP");
		}
	}
}

void APP_voidShiftLiftRight(void)
{
	for(u8 i = 0; i<4 ; i++ )
	{
		GPIO_voidSetPinValue(PORTA,PIN0,HIGH);
		Delayms(500);
		GPIO_voidSetPinValue(PORTA,PIN0,LOW);
		GPIO_voidSetPinValue(PORTA,PIN1,HIGH);
		Delayms(500);
		GPIO_voidSetPinValue(PORTA,PIN1,LOW);
		GPIO_voidSetPinValue(PORTA,PIN2,HIGH);
		Delayms(500);
		GPIO_voidSetPinValue(PORTA,PIN2,LOW);
		GPIO_voidSetPinValue(PORTA,PIN3,HIGH);
		Delayms(500);
		GPIO_voidSetPinValue(PORTA,PIN3,LOW);
		GPIO_voidSetPinValue(PORTA,PIN4,HIGH);
		Delayms(500);
		GPIO_voidSetPinValue(PORTA,PIN4,LOW);
		GPIO_voidSetPinValue(PORTA,PIN5,HIGH);
		Delayms(500);
		GPIO_voidSetPinValue(PORTA,PIN5,LOW);
		GPIO_voidSetPinValue(PORTA,PIN6,HIGH);
		Delayms(500);
		GPIO_voidSetPinValue(PORTA,PIN6,LOW);
		GPIO_voidSetPinValue(PORTA,PIN7,HIGH);
		Delayms(500);
		GPIO_voidSetPinValue(PORTA,PIN7,LOW);
		GPIO_voidSetPinValue(PORTA,PIN6,HIGH);
		Delayms(500);
		GPIO_voidSetPinValue(PORTA,PIN6,LOW);
		GPIO_voidSetPinValue(PORTA,PIN5,HIGH);
		Delayms(500);
		GPIO_voidSetPinValue(PORTA,PIN5,LOW);
		GPIO_voidSetPinValue(PORTA,PIN4,HIGH);
		Delayms(500);
		GPIO_voidSetPinValue(PORTA,PIN4,LOW);
		GPIO_voidSetPinValue(PORTA,PIN3,HIGH);
		Delayms(500);
		GPIO_voidSetPinValue(PORTA,PIN3,LOW);
		GPIO_voidSetPinValue(PORTA,PIN2,HIGH);
		Delayms(500);
		GPIO_voidSetPinValue(PORTA,PIN2,LOW);
		GPIO_voidSetPinValue(PORTA,PIN1,HIGH);
		Delayms(500);
		GPIO_voidSetPinValue(PORTA,PIN1,LOW);
		GPIO_voidSetPinValue(PORTA,PIN0,HIGH);
		Delayms(500);
		GPIO_voidSetPinValue(PORTA,PIN0,LOW);
	}

}

void APP_voidSnakeEffect(void)
{
	for(u8 i = 0; i<4 ; i++ )
	{
		GPIO_voidSetPortValue(PORTA, 0b00000001);
		Delayms(500);
		GPIO_voidSetPortValue(PORTA, 0b00000011);
		Delayms(500);
		GPIO_voidSetPortValue(PORTA, 0b00000111);
		Delayms(500);
		GPIO_voidSetPortValue(PORTA, 0b00001110);
		Delayms(500);
		GPIO_voidSetPortValue(PORTA, 0b00011100);
		Delayms(500);
		GPIO_voidSetPortValue(PORTA, 0b00111000);
		Delayms(500);
		GPIO_voidSetPortValue(PORTA, 0b01110000);
		Delayms(500);
		GPIO_voidSetPortValue(PORTA, 0b11100000);
		Delayms(500);
		GPIO_voidSetPortValue(PORTA, 0b11000000);
		Delayms(500);
		GPIO_voidSetPortValue(PORTA, 0b10000000);
		Delayms(500);
		GPIO_voidSetPortValue(PORTA, 0b00000000);
		Delayms(500);
		GPIO_voidSetPortValue(PORTA, 0b10000000);
		Delayms(500);
		GPIO_voidSetPortValue(PORTA, 0b11000000);
		Delayms(500);
		GPIO_voidSetPortValue(PORTA, 0b11100000);
		Delayms(500);
		GPIO_voidSetPortValue(PORTA, 0b01110000);
		Delayms(500);
		GPIO_voidSetPortValue(PORTA, 0b00111000);
		Delayms(500);
		GPIO_voidSetPortValue(PORTA, 0b00011100);
		Delayms(500);
		GPIO_voidSetPortValue(PORTA, 0b00001110);
		Delayms(500);
		GPIO_voidSetPortValue(PORTA, 0b00000111);
		Delayms(500);
		GPIO_voidSetPortValue(PORTA, 0b00000011);
		Delayms(500);
		GPIO_voidSetPortValue(PORTA, 0b00000001);
		Delayms(500);
		GPIO_voidSetPortValue(PORTA, 0b00000000);
	}

}

void APP_voidFatahyYawarda(void)
{
	for(u8 i=0 ; i<4 ; i++)
	{
		GPIO_voidSetPinValue(PORTA,PIN3,HIGH);
		GPIO_voidSetPinValue(PORTA,PIN4,HIGH);
		Delayms(500);
		GPIO_voidSetPinValue(PORTA,PIN2,HIGH);
		GPIO_voidSetPinValue(PORTA,PIN5,HIGH);
		Delayms(500);
		GPIO_voidSetPinValue(PORTA,PIN1,HIGH);
		GPIO_voidSetPinValue(PORTA,PIN6,HIGH);
		Delayms(500);
		GPIO_voidSetPinValue(PORTA,PIN0,HIGH);
		GPIO_voidSetPinValue(PORTA,PIN7,HIGH);
		Delayms(500);
		GPIO_voidSetPinValue(PORTA,PIN0,LOW);
		GPIO_voidSetPinValue(PORTA,PIN7,LOW);
		Delayms(500);
		GPIO_voidSetPinValue(PORTA,PIN1,LOW);
		GPIO_voidSetPinValue(PORTA,PIN6,LOW);
		Delayms(500);
		GPIO_voidSetPinValue(PORTA,PIN5,LOW);
		GPIO_voidSetPinValue(PORTA,PIN2,LOW);
		Delayms(500);
		GPIO_voidSetPinValue(PORTA,PIN4,LOW);
		GPIO_voidSetPinValue(PORTA,PIN3,LOW);
		Delayms(500);

	}

}

