/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "STD_TYPES.h"
#include "BIT_MATH.h"

#include "RCC_interface.h"
#include "GPIO_interface.h"
#include "SSD_interface.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


void Delayms(u16 Copy_u16WaitTme);	/* Simbel Delay function		    */
void DIS_voidFromXTo99(u8);		/* Display function from input number to 99 */


int main(void)
{
	RCC_voidInit();						/* Init  Clock System		*/
	RCC_voidEnablePeripheralClock(RCC_APB2,RCC_GPIOA);	/* Enable PORTA Peripheral Clock*/
	GPIO_voidSetPortDirection(PORTA, GPIO_OUTPUT_2MHZ_PP);	/* Set PORTA Direction as output*/

    /* Loop forever */
	while(1){

		DIS_voidFromXTo99(0);

	}
	return 0;
}

void Delayms(u16 Copy_u16WaitTme){
	for(u16 i=0;i<Copy_u16WaitTme;i++){
		for(u16 j=0;j<Copy_u16WaitTme;j++){
		asm	("NOP");
		}
	}
}

void DIS_voidFromXTo99(u8 Copy_u8FristNumber){
	u8 lift,right;
	right	= Copy_u8FristNumber % 10;
	lift	= Copy_u8FristNumber / 10;
	for(; lift<10; lift++){
		right = 0;
		for(;right<10;right++){
			for(u32 j = 0;j < 500; j++){
				SSD_voidDisplayNumberOnPortA(SSD_NUMBER_ONE, lift);
				Delayms(30);
				SSD_voidDisplayNumberOnPortA(SSD_NUMBER_TWO, right);
				Delayms(30);
			}
		}
	}

}

